server:
  port: 8083

spring:
  application:
    name: ems-api-gateway
  cloud:
    gateway:
      routes:
        - id: ems-department-service
          uri: lb://ems-department-service
          predicates:
            - Path=/dept-svc/**

        - id: ems-employee-service
          uri: lb://ems-employee-service
          predicates:
            - Path=/employee-svc/**
          metadata:
            cors:
              allowedOrigins: 'http://localhost:4200'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders:
                - Access-Control-Allow-Origin
                - content-type
              maxAge: 30